name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 45.91.201.124
        username: asgarda
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/plainplatform/react-movie-website
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nginx
